backend/apps/leagues/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views
app_name = 'leagues'
urlpatterns = [
    path('newLeague', views.newLeague, name='newLeague'),
    path('createLeague', views.createLeague, name='createLeague')
]

backend/apps/main/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views
app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),

]

backend/apps/users/urls.py

from django.urls import path
from .views import current_user, UserList

urlpatterns = [
    path('current_user/', current_user),
    path('users/', UserList.as_view())
]

backend/dropin/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers
from leagues.views import LeagueView

from rest_framework_jwt.views import obtain_jwt_token


router = routers.DefaultRouter()
router.register(r'leagues', LeagueView, 'league')

urlpatterns = [
    path('dropin/', include('main.urls')),
    path('leagues/', include('leagues.urls')),
    path('api/', include(router.urls)),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('token-auth/', obtain_jwt_token)


]

backend/apps/leagues/models.py
from django.db import models

# Create your models here.
class League(models.Model):
    name = models.CharField(max_length=200)
    owner = models.ForeignKey('users.User', on_delete=models.PROTECT)
    def __str__(self):
        return self.name

backend/apps/main/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import AbstractUser

from django.db import models

# Create your models here.


backend/apps/teams/models.py
from django.db import models

# Create your models here.
class Team(models.Model):
    name = models.CharField(max_length=200)
    league = models.ForeignKey("leagues.League", on_delete=models.CASCADE)
    players = models.ManyToManyField("users.User")
    def __str__(self):
        return self.name

backend/apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    pass

backend/apps/leagues/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .models import League
from .serializers import LeagueSerializer

from rest_framework import viewsets

# Create your views here.

def newLeague(request):
    return render(request, 'leagues/newLeague.html')

def createLeague(request):
    owner = request.user
    name = request.POST["leagueName"]
    league = League(name=name, owner=owner)
    league.save()
    return HttpResponseRedirect(reverse('main:index'))

class LeagueView(viewsets.ModelViewSet):
    serializer_class = LeagueSerializer
    queryset = League.objects.all()     

backend/apps/main/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from leagues.models import League
from django.views.generic.detail import DetailView


# def index(request):
#     leagues = League.objects.filter(owner=request.user)
#     context = {
#         'leagues': leagues
#     }
#     return render(request, 'home/home.html', context)

def index(request):
    return render(request, 'frontend/index.html')

backend/apps/teams/views.py
from django.shortcuts import render

# Create your views here.

backend/apps/users/views.py

from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from rest_framework import permissions, status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.views import APIView
from .serializers import UserSerializer, UserSerializerWithToken


@api_view(['GET'])
def current_user(request):
    """
    Determine the current user by their token, and return their data
    """
    
    serializer = UserSerializer(request.user)
    return Response(serializer.data)


class UserList(APIView):
    """
    Create a new user. It's called 'UserList' because normally we'd have a get
    method here too, for retrieving a list of all User objects.
    """

    permission_classes = (permissions.AllowAny,)

    def post(self, request, format=None):
        serializer = UserSerializerWithToken(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

backend/apps/leagues/templates/leagues/newLeague.html
{% extends 'base/base.html' %}
{% block main %}

<div class="container">
    <div class="row">
        <div class="col-md-9">
            <form method="post" action="{% url 'leagues:createLeague' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="leagueName">League Name</label>
                    <input class="form-control" name="leagueName" id="leagueName" aria-describedby="Name of Your League">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-sm">Create</button>
                </div>

            </form>
        </div>
    </div>

</div>

{% endblock %}

backend/apps/main/templates/base/base.html
<!doctype html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <title>Django Form Example with Bootstrap 4</title>
  </head>
  <body>
      
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="#">Dropin</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
              
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                      <a class="nav-link" href="/dropin">Home <span class="sr-only">(current)</span></a>
                    </li>
                  </ul>
                </div>
              </nav>      
          {% block main %}
          {% endblock %}

  </body>
</html>

backend/apps/main/templates/home/home.html
{% extends 'base/base.html' %}
{% block main %}

<div class="container">
    <div class="row">
        <div class="col-md-9">
            <form action="/leagues/newLeague">
                <h2 style="display:inline-block">Leagues                 
                    <button style="display:inline-block" class="btn btn-sm btn-primary" type="submit">
                        Create League
                    </button>
                </h2>
            </form>
            <table class="table" 1style="width:100%">
                <thead>
                    <th>
                        Name
                    </th>
                    <th>
                        Owner
                    </th>
                </thead>
                <tbody>
                    {% for league in leagues %}
                    <tr>
                        <td>
                            {{ league.name }}
                        </td>
                        <td>
                            {{ league.owner }}
                        </td>        
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</div>

{% endblock %}