dropinApp/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views
app_name = 'dropin'
urlpatterns = [
    path('', views.index, name='index'),
    path('newLeague', views.newLeague, name='newLeague'),
    path('createLeague', views.createLeague, name='createLeague')
]

dropinApp/templates/home/home.html
{% extends 'base/base.html' %}
{% block main %}

<div class="container">
    <div class="row">
        <div class="col-md-9">
            <form action="/dropin/newLeague">
                <h2 style="display:inline-block">Leagues                 
                    <button style="display:inline-block" class="btn btn-sm btn-primary" type="submit">
                        Create League
                    </button>
                </h2>
            </form>
            <table class="table" 1style="width:100%">
                <thead>
                    <th>
                        Name
                    </th>
                    <th>
                        Owner
                    </th>
                </thead>
                <tbody>
                    {% for league in leagues %}
                    <tr>
                        <td>
                            {{ league.name }}
                        </td>
                        <td>
                            {{ league.owner }}
                        </td>        
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</div>

{% endblock %}

dropinApp/templates/league/newLeague.html
{% extends 'base/base.html' %}
{% block main %}

<div class="container">
    <div class="row">
        <div class="col-md-9">
            <form method="post" action="{% url 'dropin:createLeague' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="leagueName">League Name</label>
                    <input class="form-control" name="leagueName" id="leagueName" aria-describedby="Name of Your League">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-sm">Create</button>
                </div>

            </form>
        </div>
    </div>

</div>

{% endblock %}